# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b915534601788140840cb424832d94143c04fe21d6bf21a4706ed21f35fba77d9f7d04ae977516d1217e3c8d62869a0e580516128c5bfea362460f37c448b130

test:
  secret_key_base: b4ce26b66da5b40147881962bd1b7ad0c1b974b31edf32c1cd1f78ac6c0a61d24d41cfa2e47d4b20c8759dbbdf4691d5f6496d8dcf4829496ec8e9704c54ca16

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
